import {DropdownItemProps} from "semantic-ui-react";

export const STATE_OPTIONS = [
  { key: 'AL', value: 'AL', text: 'Alabama' },
  { key: 'AK', value: 'AK', text: 'Alaska' },
  { key: 'AZ', value: 'AZ', text: 'Arizona' },
  { key: 'AR', value: 'AR', text: 'Arkansas' },
  { key: 'CA', value: 'CA', text: 'California' },
  { key: 'CO', value: 'CO', text: 'Colorado' },
  { key: 'CT', value: 'CT', text: 'Connecticut' },
  { key: 'DE', value: 'DE', text: 'Delaware' },
  { key: 'DC', value: 'DC', text: 'District Of Columbia' },
  { key: 'FL', value: 'FL', text: 'Florida' },
  { key: 'GA', value: 'GA', text: 'Georgia' },
  { key: 'HI', value: 'HI', text: 'Hawaii' },
  { key: 'ID', value: 'ID', text: 'Idaho' },
  { key: 'IL', value: 'IL', text: 'Illinois' },
  { key: 'IN', value: 'IN', text: 'Indiana' },
  { key: 'IA', value: 'IA', text: 'Iowa' },
  { key: 'KS', value: 'KS', text: 'Kansas' },
  { key: 'KY', value: 'KY', text: 'Kentucky' },
  { key: 'LA', value: 'LA', text: 'Louisiana' },
  { key: 'ME', value: 'ME', text: 'Maine' },
  { key: 'MD', value: 'MD', text: 'Maryland' },
  { key: 'MA', value: 'MA', text: 'Massachusetts' },
  { key: 'MI', value: 'MI', text: 'Michigan' },
  { key: 'MN', value: 'MN', text: 'Minnesota' },
  { key: 'MS', value: 'MS', text: 'Mississippi' },
  { key: 'MO', value: 'MO', text: 'Missouri' },
  { key: 'MT', value: 'MT', text: 'Montana' },
  { key: 'NE', value: 'NE', text: 'Nebraska' },
  { key: 'NV', value: 'NV', text: 'Nevada' },
  { key: 'NH', value: 'NH', text: 'New Hampshire' },
  { key: 'NJ', value: 'NJ', text: 'New Jersey' },
  { key: 'NM', value: 'NM', text: 'New Mexico' },
  { key: 'NY', value: 'NY', text: 'New York' },
  { key: 'NC', value: 'NC', text: 'North Carolina' },
  { key: 'ND', value: 'ND', text: 'North Dakota' },
  { key: 'OH', value: 'OH', text: 'Ohio' },
  { key: 'OK', value: 'OK', text: 'Oklahoma' },
  { key: 'OR', value: 'OR', text: 'Oregon' },
  { key: 'PA', value: 'PA', text: 'Pennsylvania' },
  { key: 'RI', value: 'RI', text: 'Rhode Island' },
  { key: 'SC', value: 'SC', text: 'South Carolina' },
  { key: 'SD', value: 'SD', text: 'South Dakota' },
  { key: 'TN', value: 'TN', text: 'Tennessee' },
  { key: 'TX', value: 'TX', text: 'Texas' },
  { key: 'UT', value: 'UT', text: 'Utah' },
  { key: 'VT', value: 'VT', text: 'Vermont' },
  { key: 'VA', value: 'VA', text: 'Virginia' },
  { key: 'WA', value: 'WA', text: 'Washington' },
  { key: 'WV', value: 'WV', text: 'West Virginia' },
  { key: 'WI', value: 'WI', text: 'Wisconsin' },
  { key: 'WY', value: 'WY', text: 'Wyoming' },
];

export const LANGUAGE_OPTIONS = [
  { key: 'Arabic', text: 'Arabic', value: 'Arabic' },
  { key: 'Chinese', text: 'Chinese', value: 'Chinese' },
  { key: 'Danish', text: 'Danish', value: 'Danish' },
  { key: 'Dutch', text: 'Dutch', value: 'Dutch' },
  { key: 'English', text: 'English', value: 'English' },
  { key: 'French', text: 'French', value: 'French' },
  { key: 'German', text: 'German', value: 'German' },
  { key: 'Greek', text: 'Greek', value: 'Greek' },
  { key: 'Hungarian', text: 'Hungarian', value: 'Hungarian' },
  { key: 'Italian', text: 'Italian', value: 'Italian' },
  { key: 'Japanese', text: 'Japanese', value: 'Japanese' },
  { key: 'Korean', text: 'Korean', value: 'Korean' },
  { key: 'Lithuanian', text: 'Lithuanian', value: 'Lithuanian' },
  { key: 'Persian', text: 'Persian', value: 'Persian' },
  { key: 'Polish', text: 'Polish', value: 'Polish' },
  { key: 'Portuguese', text: 'Portuguese', value: 'Portuguese' },
  { key: 'Russian', text: 'Russian', value: 'Russian' },
  { key: 'Spanish', text: 'Spanish', value: 'Spanish' },
  { key: 'Swedish', text: 'Swedish', value: 'Swedish' },
  { key: 'Turkish', text: 'Turkish', value: 'Turkish' },
  { key: 'Vietnamese', text: 'Vietnamese', value: 'Vietnamese' },
];

export const TAG_OPTIONS = [
  {
    key: 'Important',
    text: 'Important',
    value: 'Important',
    label: { color: 'red', empty: true, circular: true },
  },
  {
    key: 'Announcement',
    text: 'Announcement',
    value: 'Announcement',
    label: { color: 'blue', empty: true, circular: true },
  },
  {
    key: 'Cannot Fix',
    text: 'Cannot Fix',
    value: 'Cannot Fix',
    label: { color: 'black', empty: true, circular: true },
  },
  {
    key: 'News',
    text: 'News',
    value: 'News',
    label: { color: 'purple', empty: true, circular: true },
  },
  {
    key: 'Enhancement',
    text: 'Enhancement',
    value: 'Enhancement',
    label: { color: 'orange', empty: true, circular: true },
  },
  {
    key: 'Change Declined',
    text: 'Change Declined',
    value: 'Change Declined',
    label: { empty: true, circular: true },
  },
  {
    key: 'Off Topic',
    text: 'Off Topic',
    value: 'Off Topic',
    label: { color: 'yellow', empty: true, circular: true },
  },
  {
    key: 'Interesting',
    text: 'Interesting',
    value: 'Interesting',
    label: { color: 'pink', empty: true, circular: true },
  },
  {
    key: 'Discussion',
    text: 'Discussion',
    value: 'Discussion',
    label: { color: 'green', empty: true, circular: true },
  },
];

export type FlagNames = 
  'ad' | 'andorra' | 'ae' | 'united arab emirates' | 'uae' | 'af' | 'afghanistan' | 'ag' | 'antigua' | 'ai' |
  'anguilla' | 'al' | 'albania' | 'am' | 'armenia' | 'an' | 'netherlands antilles' | 'ao' | 'angola' | 'ar' |
  'argentina' | 'as' | 'american samoa' | 'at' | 'austria' | 'au' | 'australia' | 'aw' | 'aruba' | 'ax' |
  'aland islands' | 'az' | 'azerbaijan' | 'ba' | 'bosnia' | 'bb' | 'barbados' | 'bd' | 'bangladesh' | 'be' |
  'belgium' | 'bf' | 'burkina faso' | 'bg' | 'bulgaria' | 'bh' | 'bahrain' | 'bi' | 'burundi' | 'bj' | 'benin' |
  'bm' | 'bermuda' | 'bn' | 'brunei' | 'bo' | 'bolivia' | 'br' | 'brazil' | 'bs' | 'bahamas' | 'bt' | 'bhutan' |
  'bv' | 'bouvet island' | 'bw' | 'botswana' | 'by' | 'belarus' | 'bz' | 'belize' | 'ca' | 'canada' | 'cc' |
  'cocos islands' | 'cd' | 'congo' | 'cf' | 'central african republic' | 'cg' | 'congo brazzaville' | 'ch' |
  'switzerland' | 'ci' | 'cote divoire' | 'ck' | 'cook islands' | 'cl' | 'chile' | 'cm' | 'cameroon' | 'cn' |
  'china' | 'co' | 'colombia' | 'cr' | 'costa rica' | 'cs' | 'cu' | 'cuba' | 'cv' | 'cape verde' | 'cx' |
  'christmas island' | 'cy' | 'cyprus' | 'cz' | 'czech republic' | 'de' | 'germany' | 'dj' | 'djibouti' | 'dk' |
  'denmark' | 'dm' | 'dominica' | 'do' | 'dominican republic' | 'dz' | 'algeria' | 'ec' | 'ecuador' | 'ee' |
  'estonia' | 'eg' | 'egypt' | 'eh' | 'western sahara' | 'er' | 'eritrea' | 'es' | 'spain' | 'et' | 'ethiopia' |
  'eu' | 'european union' | 'fi' | 'finland' | 'fj' | 'fiji' | 'fk' | 'falkland islands' | 'fm' | 'micronesia' |
  'fo' | 'faroe islands' | 'fr' | 'france' | 'ga' | 'gabon' | 'gb' | 'united kingdom' | 'gd' | 'grenada' | 'ge' |
  'georgia' | 'gf' | 'french guiana' | 'gh' | 'ghana' | 'gi' | 'gibraltar' | 'gl' | 'greenland' | 'gm' | 'gambia' |
  'gn' | 'guinea' | 'gp' | 'guadeloupe' | 'gq' | 'equatorial guinea' | 'gr' | 'greece' | 'gs' | 'sandwich islands' |
  'gt' | 'guatemala' | 'gu' | 'guam' | 'gw' | 'guinea-bissau' | 'gy' | 'guyana' | 'hk' | 'hong kong' | 'hm' |
  'heard island' | 'hn' | 'honduras' | 'hr' | 'croatia' | 'ht' | 'haiti' | 'hu' | 'hungary' | 'id' | 'indonesia' |
  'ie' | 'ireland' | 'il' | 'israel' | 'in' | 'india' | 'io' | 'indian ocean territory' | 'iq' | 'iraq' | 'ir' |
  'iran' | 'is' | 'iceland' | 'it' | 'italy' | 'jm' | 'jamaica' | 'jo' | 'jordan' | 'jp' | 'japan' | 'ke' | 'kenya' |
  'kg' | 'kyrgyzstan' | 'kh' | 'cambodia' | 'ki' | 'kiribati' | 'km' | 'comoros' | 'kn' | 'saint kitts and nevis' |
  'kp' | 'north korea' | 'kr' | 'south korea' | 'kw' | 'kuwait' | 'ky' | 'cayman islands' | 'kz' | 'kazakhstan' |
  'la' | 'laos' | 'lb' | 'lebanon' | 'lc' | 'saint lucia' | 'li' | 'liechtenstein' | 'lk' | 'sri lanka' | 'lr' |
  'liberia' | 'ls' | 'lesotho' | 'lt' | 'lithuania' | 'lu' | 'luxembourg' | 'lv' | 'latvia' | 'ly' | 'libya' | 'ma' |
  'morocco' | 'mc' | 'monaco' | 'md' | 'moldova' | 'me' | 'montenegro' | 'mg' | 'madagascar' | 'mh' |
  'marshall islands' | 'mk' | 'macedonia' | 'ml' | 'mali' | 'mm' | 'myanmar' | 'burma' | 'mn' | 'mongolia' | 'mo' |
  'macau' | 'mp' | 'northern mariana islands' | 'mq' | 'martinique' | 'mr' | 'mauritania' | 'ms' | 'montserrat' |
  'mt' | 'malta' | 'mu' | 'mauritius' | 'mv' | 'maldives' | 'mw' | 'malawi' | 'mx' | 'mexico' | 'my' | 'malaysia' |
  'mz' | 'mozambique' | 'na' | 'namibia' | 'nc' | 'new caledonia' | 'ne' | 'niger' | 'nf' | 'norfolk island' | 'ng' |
  'nigeria' | 'ni' | 'nicaragua' | 'nl' | 'netherlands' | 'no' | 'norway' | 'np' | 'nepal' | 'nr' | 'nauru' |
  'nu' | 'niue' | 'nz' | 'new zealand' | 'om' | 'oman' | 'pa' | 'panama' | 'pe' | 'peru' | 'pf' | 'french polynesia' |
  'pg' | 'new guinea' | 'ph' | 'philippines' | 'pk' | 'pakistan' | 'pl' | 'poland' | 'pm' | 'saint pierre' | 'pn' |
  'pitcairn islands' | 'pr' | 'puerto rico' | 'ps' | 'palestine' | 'pt' | 'portugal' | 'pw' | 'palau' | 'py' |
  'paraguay' | 'qa' | 'qatar' | 're' | 'reunion' | 'ro' | 'romania' | 'rs' | 'serbia' | 'ru' | 'russia' | 'rw' |
  'rwanda' | 'sa' | 'saudi arabia' | 'sb' | 'solomon islands' | 'sc' | 'seychelles' | 'gb sct' | 'scotland' | 'sd' |
  'sudan' | 'se' | 'sweden' | 'sg' | 'singapore' | 'sh' | 'saint helena' | 'si' | 'slovenia' | 'sj' | 'svalbard' |
  'jan mayen' | 'sk' | 'slovakia' | 'sl' | 'sierra leone' | 'sm' | 'san marino' | 'sn' | 'senegal' | 'so' |
  'somalia' | 'sr' | 'suriname' | 'st' | 'sao tome' | 'sv' | 'el salvador' | 'sy' | 'syria' | 'sz' | 'swaziland' |
  'tc' | 'caicos islands' | 'td' | 'chad' | 'tf' | 'french territories' | 'tg' | 'togo' | 'th' | 'thailand' | 'tj' |
  'tajikistan' | 'tk' | 'tokelau' | 'tl' | 'timorleste' | 'tm' | 'turkmenistan' | 'tn' | 'tunisia' | 'to' | 'tonga' |
  'tr' | 'turkey' | 'tt' | 'trinidad' | 'tv' | 'tuvalu' | 'tw' | 'taiwan' | 'tz' | 'tanzania' | 'ua' | 'ukraine' |
  'ug' | 'uganda' | 'um' | 'us minor islands' | 'us' | 'america' | 'united states' | 'uy' | 'uruguay' | 'uz' |
  'uzbekistan' | 'va' | 'vatican city' | 'vc' | 'saint vincent' | 've' | 'venezuela' | 'vg' |
  'british virgin islands' | 'vi' | 'us virgin islands' | 'vn' | 'vietnam' | 'vu' | 'vanuatu' | 'gb wls' | 'wales' |
  'wf' | 'wallis and futuna' | 'ws' | 'samoa' | 'ye' | 'yemen' | 'yt' | 'mayotte' | 'za' | 'south africa' | 'zm' |
  'zambia' | 'zw' | 'zimbabwe';

export const COUNTRY_OPTIONS = [
  {key: 'af', value: 'af', flag: 'af', text: 'Afghanistan'},
  //{key: 'ax', value: 'ax', flag: 'ax', text: 'Åland Islands'},
  {key: 'al', value: 'al', flag: 'al', text: 'Albania'},
  {key: 'dz', value: 'dz', flag: 'dz', text: 'Algeria'},
  {key: 'ad', value: 'ad', flag: 'ad', text: 'Andorra'},
  {key: 'ao', value: 'ao', flag: 'ao', text: 'Angola'},
  {key: 'ai', value: 'ai', flag: 'ai', text: 'Anguilla'},
  {key: 'aq', value: 'aq', flag: 'aq', text: 'Antarctica'},
  {key: 'ag', value: 'ag', flag: 'ag', text: 'Antigua và Barbuda'},
  {key: 'ar', value: 'ar', flag: 'ar', text: 'Argentina'},
  {key: 'am', value: 'am', flag: 'am', text: 'Armenia'},
  //{key: 'aw', value: 'aw', flag: 'aw', text: 'Aruba'},
  {key: 'au', value: 'au', flag: 'au', text: 'Úc'},
  {key: 'at', value: 'at', flag: 'at', text: 'Áo'},
  {key: 'az', value: 'az', flag: 'az', text: 'Azerbaijan'},
  {key: 'bs', value: 'bs', flag: 'bs', text: 'Bahamas'},
  {key: 'bh', value: 'bh', flag: 'bh', text: 'Bahrain'},
  {key: 'bd', value: 'bd', flag: 'bd', text: 'Bangladesh'},
  {key: 'bb', value: 'bb', flag: 'bb', text: 'Barbados'},
  {key: 'by', value: 'by', flag: 'by', text: 'Belarus'},
  {key: 'be', value: 'be', flag: 'be', text: 'Bỉ'},
  {key: 'bz', value: 'bz', flag: 'bz', text: 'Belize'},
  {key: 'bj', value: 'bj', flag: 'bj', text: 'Benin'},
  //{key: 'bm', value: 'bm', flag: 'bm', text: 'Bermuda'},
  {key: 'bt', value: 'bt', flag: 'bt', text: 'Bhutan'},
  {key: 'bo', value: 'bo', flag: 'bo', text: 'Bolivia'},
  // {key: 'bq', value: 'bq', flag: 'bq', text: 'Bonaire, Sint Eustatius and Saba'},
  {key: 'ba', value: 'ba', flag: 'ba', text: 'Bosnia và Herzegovina'},
  {key: 'bw', value: 'bw', flag: 'bw', text: 'Botswana'},
  {key: 'br', value: 'br', flag: 'br', text: 'Brazil'},
  // {key: 'vg', value: 'vg', flag: 'vg', text: 'Virgin Islands (British)'},
  {key: 'bn', value: 'bn', flag: 'bn', text: 'Brunei Darussalam'},
  {key: 'bg', value: 'bg', flag: 'bg', text: 'Bulgaria'},
  {key: 'bf', value: 'bf', flag: 'bf', text: 'Burkina Faso'},
  {key: 'bi', value: 'bi', flag: 'bi', text: 'Burundi'},
  //{key: 'tc', value: 'tc', flag: 'tc', text: 'Các đảo Turks và Caicos'},
  {key: 'kh', value: 'kh', flag: 'kh', text: 'Campuchia'},
  {key: 'cm', value: 'cm', flag: 'cm', text: 'Cameroon'},
  {key: 'ca', value: 'ca', flag: 'ca', text: 'Canada'},
  {key: 'cv', value: 'cv', flag: 'cv', text: 'Cabo Verde'},
  //{key: 'ky', value: 'ky', flag: 'ky', text: 'Cayman Islands'},
  {key: 'cf', value: 'cf', flag: 'cf', text: 'Cộng hòa Trung Phi'},
  {key: 'td', value: 'td', flag: 'td', text: 'Chad'},
  {key: 'cl', value: 'cl', flag: 'cl', text: 'Chile'},
  {key: 'cn', value: 'cn', flag: 'cn', text: 'Trung Quốc'},
  {key: 'cx', value: 'cx', flag: 'cx', text: 'Đảo Giáng Sinh'},
  {key: 'cc', value: 'cc', flag: 'cc', text: 'Cocos (Keeling) Islands'},
  {key: 'co', value: 'co', flag: 'co', text: 'Colombia'},
  {key: 'km', value: 'km', flag: 'km', text: 'Comoros'},
  {key: 'cg', value: 'cg', flag: 'cg', text: 'Cộng hòa Congo'},
  {key: 'cd', value: 'cd', flag: 'cd', text: 'CHDC Congo'},
  //{key: 'ck', value: 'ck', flag: 'ck', text: 'Đảo Cook'},
  {key: 'cr', value: 'cr', flag: 'cr', text: 'Costa Rica'},
  {key: 'ci', value: 'ci', flag: 'ci', text: 'Bờ Biển Ngà'},
  {key: 'hr', value: 'hr', flag: 'hr', text: 'Croatia'},
  {key: 'cu', value: 'cu', flag: 'cu', text: 'Cuba'},
  {key: 'cw', value: 'cw', flag: 'cw', text: 'Curaçao'},
  {key: 'cy', value: 'cy', flag: 'cy', text: 'Cyprus'},
  {key: 'cz', value: 'cz', flag: 'cz', text: 'Cộng hòa Séc'},
  {key: 'dk', value: 'dk', flag: 'dk', text: 'Đan Mạch'},
  {key: 'dj', value: 'dj', flag: 'dj', text: 'Djibouti'},
  {key: 'dm', value: 'dm', flag: 'dm', text: 'Dominica'},
  {key: 'do', value: 'do', flag: 'do', text: 'Cộng hòa Dominica'},
  {key: 'ec', value: 'ec', flag: 'ec', text: 'Ecuador'},
  {key: 'eg', value: 'eg', flag: 'eg', text: 'Ai Cập'},
  {key: 'sv', value: 'sv', flag: 'sv', text: 'El Salvador'},
  {key: 'gb', value: 'gb', flag: 'gb', text: 'Vương quốc Anh'},
  {key: 'gq', value: 'gq', flag: 'gq', text: 'Guinea Xích đạo'},
  {key: 'er', value: 'er', flag: 'er', text: 'Eritrea'},
  {key: 'ee', value: 'ee', flag: 'ee', text: 'Estonia'},
  {key: 'et', value: 'et', flag: 'et', text: 'Ethiopia'},
  {key: 'eu', value: 'eu', flag: 'eu', text: 'Liên minh châu Âu'},
  //{key: 'fk', value: 'fk', flag: 'fk', text: 'Falkland Islands'},
  //{key: 'fo', value: 'fo', flag: 'fo', text: 'Faroe Islands'},
  {key: 'fj', value: 'fj', flag: 'fj', text: 'Fiji'},
  {key: 'fi', value: 'fi', flag: 'fi', text: 'Phần Lan'},
  {key: 'fr', value: 'fr', flag: 'fr', text: 'Pháp'},
  //{key: 'gf', value: 'gf', flag: 'gf', text: 'French Guiana'},
  //{key: 'pf', value: 'pf', flag: 'pf', text: 'French Polynesia'},
  //{key: 'tf', value: 'tf', flag: 'tf', text: 'French Southern Territories'},
  {key: 'ga', value: 'ga', flag: 'ga', text: 'Gabon'},
  {key: 'gm', value: 'gm', flag: 'gm', text: 'Gambia'},
  {key: 'ge', value: 'ge', flag: 'ge', text: 'Georgia'},
  {key: 'de', value: 'de', flag: 'de', text: 'Đức'},
  {key: 'gh', value: 'gh', flag: 'gh', text: 'Ghana'},
  //{key: 'gi', value: 'gi', flag: 'gi', text: 'Gibraltar'},
  {key: 'gr', value: 'gr', flag: 'gr', text: 'Hy Lạp'},
  {key: 'gl', value: 'gl', flag: 'gl', text: 'Greenland'},
  {key: 'gd', value: 'gd', flag: 'gd', text: 'Grenada'},
  //{key: 'gp', value: 'gp', flag: 'gp', text: 'Guadeloupe'},
  //{key: 'gu', value: 'gu', flag: 'gu', text: 'Guam'},
  {key: 'gt', value: 'gt', flag: 'gt', text: 'Guatemala'},
  //{key: 'gg', value: 'gg', flag: 'gg', text: 'Guernsey'},
  {key: 'gw', value: 'gw', flag: 'gw', text: 'Guinea-Bissau'},
  {key: 'gn', value: 'gn', flag: 'gn', text: 'Guinea'},
  {key: 'gy', value: 'gy', flag: 'gy', text: 'Guyana'},
  {key: 'ht', value: 'ht', flag: 'ht', text: 'Haiti'},
  //{key: 'hm', value: 'hm', flag: 'hm', text: 'Heard Island and McDonald Islands'},
  {key: 'hn', value: 'hn', flag: 'hn', text: 'Honduras'},
  {key: 'hu', value: 'hu', flag: 'hu', text: 'Hungary'},
  {key: 'is', value: 'is', flag: 'is', text: 'Iceland'},
  {key: 'in', value: 'in', flag: 'in', text: 'Ấn Độ'},
  //{key: 'io', value: 'io', flag: 'io', text: 'British Indian Ocean Territory'},
  {key: 'id', value: 'id', flag: 'id', text: 'Indonesia'},
  {key: 'ir', value: 'ir', flag: 'ir', text: 'Iran'},
  {key: 'iq', value: 'iq', flag: 'iq', text: 'Iraq'},
  {key: 'ie', value: 'ie', flag: 'ie', text: 'Ireland'},
  //{key: 'im', value: 'im', flag: 'im', text: 'Isle of Man'},
  {key: 'il', value: 'il', flag: 'il', text: 'Israel'},
  {key: 'it', value: 'it', flag: 'it', text: 'Ý'},
  {key: 'jm', value: 'jm', flag: 'jm', text: 'Jamaica'},
  {key: 'jp', value: 'jp', flag: 'jp', text: 'Nhật Bản'},
  {key: 'jo', value: 'jo', flag: 'jo', text: 'Jordan'},
  {key: 'kz', value: 'kz', flag: 'kz', text: 'Kazakhstan'},
  {key: 'ke', value: 'ke', flag: 'ke', text: 'Kenya'},
  {key: 'ki', value: 'ki', flag: 'ki', text: 'Kiribati'},
  {key: 'kw', value: 'kw', flag: 'kw', text: 'Kuwait'},
  {key: 'kg', value: 'kg', flag: 'kg', text: 'Kyrgyzstan'},
  {key: 'la', value: 'la', flag: 'la', text: 'Lào'},
  {key: 'lv', value: 'lv', flag: 'lv', text: 'Latvia'},
  {key: 'lb', value: 'lb', flag: 'lb', text: 'Lebanon'},
  {key: 'ls', value: 'ls', flag: 'ls', text: 'Lesotho'},
  {key: 'lr', value: 'lr', flag: 'lr', text: 'Liberia'},
  {key: 'ly', value: 'ly', flag: 'ly', text: 'Libya'},
  {key: 'li', value: 'li', flag: 'li', text: 'Liechtenstein'},
  {key: 'lt', value: 'lt', flag: 'lt', text: 'Lithuania'},
  {key: 'lu', value: 'lu', flag: 'lu', text: 'Luxembourg'},
  {key: 'mo', value: 'mo', flag: 'mo', text: 'Macao'},
  {key: 'mk', value: 'mk', flag: 'mk', text: 'Bắc Macedonia'}, // renamed in 2019
  {key: 'mg', value: 'mg', flag: 'mg', text: 'Madagascar'},
  {key: 'mw', value: 'mw', flag: 'mw', text: 'Malawi'},
  {key: 'my', value: 'my', flag: 'my', text: 'Malaysia'},
  {key: 'mv', value: 'mv', flag: 'mv', text: 'Maldives'},
  {key: 'ml', value: 'ml', flag: 'ml', text: 'Mali'},
  {key: 'mt', value: 'mt', flag: 'mt', text: 'Malta'},
  {key: 'mh', value: 'mh', flag: 'mh', text: 'Marshall Islands'},
  //{key: 'mq', value: 'mq', flag: 'mq', text: 'Martinique'},
  {key: 'mr', value: 'mr', flag: 'mr', text: 'Mauritania'},
  {key: 'mu', value: 'mu', flag: 'mu', text: 'Mauritius'},
  //{key: 'yt', value: 'yt', flag: 'yt', text: 'Mayotte'},
  {key: 'mx', value: 'mx', flag: 'mx', text: 'Mexico'},
  //{key: 'fm', value: 'fm', flag: 'fm', text: 'Micronesia (Federated States of)'},
  {key: 'md', value: 'md', flag: 'md', text: 'Moldova'},
  {key: 'mc', value: 'mc', flag: 'mc', text: 'Monaco'},
  {key: 'mn', value: 'mn', flag: 'mn', text: 'Mông Cổ'},
  {key: 'me', value: 'me', flag: 'me', text: 'Montenegro'},
  {key: 'ma', value: 'ma', flag: 'ma', text: 'Morocco'},
  {key: 'mz', value: 'mz', flag: 'mz', text: 'Mozambique'},
  {key: 'mm', value: 'mm', flag: 'mm', text: 'Myanmar'},
  {key: 'na', value: 'na', flag: 'na', text: 'Namibia'},
  {key: 'nr', value: 'nr', flag: 'nr', text: 'Nauru'},
  {key: 'np', value: 'np', flag: 'np', text: 'Nepal'},
  {key: 'nl', value: 'nl', flag: 'nl', text: 'Hà Lan'},
  //{key: 'nc', value: 'nc', flag: 'nc', text: 'New Caledonia'},
  {key: 'pg', value: 'pg', flag: 'pg', text: 'Papua New Guinea'},
  {key: 'nz', value: 'nz', flag: 'nz', text: 'New Zealand'},
  {key: 'ni', value: 'ni', flag: 'ni', text: 'Nicaragua'},
  {key: 'ne', value: 'ne', flag: 'ne', text: 'Niger'},
  {key: 'ng', value: 'ng', flag: 'ng', text: 'Nigeria'},
  //{key: 'nu', value: 'nu', flag: 'nu', text: 'Niue'},
  //{key: 'nf', value: 'nf', flag: 'nf', text: 'Norfolk Island'},
  {key: 'kp', value: 'kp', flag: 'kp', text: 'CHDCND Triều Tiên'},
  //{key: 'mp', value: 'mp', flag: 'mp', text: 'Northern Mariana Islands'},
  {key: 'no', value: 'no', flag: 'no', text: 'Na Uy'},
  {key: 'om', value: 'om', flag: 'om', text: 'Oman'},
  {key: 'pk', value: 'pk', flag: 'pk', text: 'Pakistan'},
  {key: 'pw', value: 'pw', flag: 'pw', text: 'Palau'},
  {key: 'ps', value: 'ps', flag: 'ps', text: 'Nhà nước Palestine'},
  {key: 'pa', value: 'pa', flag: 'pa', text: 'Panama'},
  {key: 'py', value: 'py', flag: 'py', text: 'Paraguay'},
  {key: 'pe', value: 'pe', flag: 'pe', text: 'Peru'},
  {key: 'ph', value: 'ph', flag: 'ph', text: 'Philippines'},
  {key: 'pl', value: 'pl', flag: 'pl', text: 'Ba Lan'},
  {key: 'pt', value: 'pt', flag: 'pt', text: 'Bồ Đào Nha'},
  //{key: 'pr', value: 'pr', flag: 'pr', text: 'Puerto Rico'},
  {key: 'qa', value: 'qa', flag: 'qa', text: 'Qatar'},
  //{key: 're', value: 're', flag: 're', text: 'Đảo Réunion'},
  {key: 'ro', value: 'ro', flag: 'ro', text: 'Romania'},
  {key: 'ru', value: 'ru', flag: 'ru', text: 'Nga'},
  {key: 'rw', value: 'rw', flag: 'rw', text: 'Rwanda'},
  //{key: 'bl', value: 'bl', flag: 'bl', text: 'Saint Barthélemy'},
  //{key: 'sh', value: 'sh', flag: 'sh', text: 'Saint Helena, Ascension and Tristan da Cunha'},
  {key: 'kn', value: 'kn', flag: 'kn', text: 'Saint Kitts và Nevis'},
  {key: 'lc', value: 'lc', flag: 'lc', text: 'Saint Lucia'},
  //{key: 'mf', value: 'mf', flag: 'mf', text: 'Saint Martin (French part)'},
  //{key: 'pm', value: 'pm', flag: 'pm', text: 'Saint Pierre and Miquelon'},
  {key: 'vc', value: 'vc', flag: 'vc', text: 'Saint Vincent and the Grenadines'},
  {key: 'ws', value: 'ws', flag: 'ws', text: 'Samoa'},
  {key: 'sm', value: 'sm', flag: 'sm', text: 'San Marino'},
  //{key: 'gs', value: 'gs', flag: 'gs', text: 'South Georgia and the South Sandwich Islands'},
  {key: 'st', value: 'st', flag: 'st', text: 'Sao Tome và Principe'},
  {key: 'sa', value: 'sa', flag: 'sa', text: 'Ả-rập Xê-út'},
  {key: 'sn', value: 'sn', flag: 'sn', text: 'Senegal'},
  {key: 'rs', value: 'rs', flag: 'rs', text: 'Serbia'},
  {key: 'sc', value: 'sc', flag: 'sc', text: 'Seychelles'},
  {key: 'sl', value: 'sl', flag: 'sl', text: 'Sierra Leone'},
  {key: 'sg', value: 'sg', flag: 'sg', text: 'Singapore'},
  //{key: 'sx', value: 'sx', flag: 'sx', text: 'Sint Maarten (Dutch part)'},
  {key: 'sk', value: 'sk', flag: 'sk', text: 'Slovakia'},
  {key: 'si', value: 'si', flag: 'si', text: 'Slovenia'},
  {key: 'sb', value: 'sb', flag: 'sb', text: 'Solomon Islands'},
  {key: 'so', value: 'so', flag: 'so', text: 'Somalia'},
  {key: 'za', value: 'za', flag: 'za', text: 'Nam Phi'},
  {key: 'kr', value: 'kr', flag: 'kr', text: 'Hàn Quốc'},
  {key: 'ss', value: 'ss', flag: 'ss', text: 'Nam Sudan'},
  {key: 'es', value: 'es', flag: 'es', text: 'Tây Ban Nha'},
  {key: 'lk', value: 'lk', flag: 'lk', text: 'Sri Lanka'},
  {key: 'sd', value: 'sd', flag: 'sd', text: 'Sudan'},
  {key: 'sr', value: 'sr', flag: 'sr', text: 'Suriname'},
  //{key: 'sj', value: 'sj', flag: 'sj', text: 'Svalbard và Jan Mayen'},
  {key: 'sz', value: 'sz', flag: 'sz', text: 'Eswatini'}, // renamed in 2018 (was Swaziland)
  {key: 'se', value: 'se', flag: 'se', text: 'Thụy Điển'},
  {key: 'ch', value: 'ch', flag: 'ch', text: 'Thụy Sĩ'},
  {key: 'sy', value: 'sy', flag: 'sy', text: 'Syria'},
  {key: 'tj', value: 'tj', flag: 'tj', text: 'Tajikistan'},
  {key: 'tz', value: 'tz', flag: 'tz', text: 'Tanzania'},
  {key: 'th', value: 'th', flag: 'th', text: 'Thái Lan'},
  {key: 'tl', value: 'tl', flag: 'tl', text: 'Timor-Leste'},
  {key: 'tg', value: 'tg', flag: 'tg', text: 'Togo'},
  //{key: 'tk', value: 'tk', flag: 'tk', text: 'Tokelau'},
  {key: 'to', value: 'to', flag: 'to', text: 'Tonga'},
  {key: 'tt', value: 'tt', flag: 'tt', text: 'Trinidad and Tobago'},
  {key: 'tn', value: 'tn', flag: 'tn', text: 'Tunisia'},
  {key: 'tr', value: 'tr', flag: 'tr', text: 'Thổ Nhĩ Kỳ'},
  {key: 'tm', value: 'tm', flag: 'tm', text: 'Turkmenistan'},
  {key: 'tv', value: 'tv', flag: 'tv', text: 'Tuvalu'},
  {key: 'ug', value: 'ug', flag: 'ug', text: 'Uganda'},
  {key: 'ua', value: 'ua', flag: 'ua', text: 'Ukraine'},
  {key: 'ae', value: 'ae', flag: 'ae', text: 'Các Tiểu vương quốc Arab thống nhất'},
  {key: 'us', value: 'us', flag: 'us', text: 'Hoa Kỳ'},
  {key: 'uy', value: 'uy', flag: 'uy', text: 'Uruguay'},
  //{key: 'um', value: 'um', flag: 'um', text: 'United States Minor Outlying Islands'},
  //{key: 'vi', value: 'vi', flag: 'vi', text: 'Virgin Islands (U.S.)'},
  {key: 'uz', value: 'uz', flag: 'uz', text: 'Uzbekistan'},
  {key: 'vu', value: 'vu', flag: 'vu', text: 'Vanuatu'},
  {key: 'va', value: 'va', flag: 'va', text: 'Thành Vatican'},
  {key: 've', value: 've', flag: 've', text: 'Venezuela'},
  {key: 'vn', value: 'vn', flag: 'vn', text: 'Việt Nam'},
  //{key: 'wf', value: 'wf', flag: 'wf', text: 'Wallis và Futuna'},
  {key: 'eh', value: 'eh', flag: 'eh', text: 'Tây Sahara'},
  {key: 'ye', value: 'ye', flag: 'ye', text: 'Yemen'},
  {key: 'zm', value: 'zm', flag: 'zm', text: 'Zambia'},
  {key: 'zw', value: 'zw', flag: 'zw', text: 'Zimbabwe'},
].sort((a, b) => a.text.localeCompare(b.text));

// Firebase stores member names rather than ISO codes. Keep every previously
// shipped name resolvable so existing committees continue to get the correct
// option and flag after the canonical display name changes.
export const COUNTRY_NAME_ALIASES: Readonly<Record<string, string>> = {
  'Aland Islands': 'ax',
  'Antigua': 'ag',
  'Bolivia': 'bo',
  'Bosnia': 'ba',
  'Brunei': 'bn',
  'British Virgin Islands': 'vg',
  'Burma': 'mm',
  'Caicos Islands': 'tc',
  'Cape Verde': 'cv',
  'Cocos Islands': 'cc',
  'Congo': 'cd',
  'Congo Brazzaville': 'cg',
  'Cote Divoire': 'ci',
  "Cote d'Ivoire": 'ci',
  'Czech Republic': 'cz',
  'East Timor': 'tl',
  'Falkland Islands': 'fk',
  'French Territories': 'tf',
  'Heard Island': 'hm',
  'Indian Ocean Territory': 'io',
  'Iran': 'ir',
  'Ivory Coast': 'ci',
  'Laos': 'la',
  'Macau': 'mo',
  'Macedonia': 'mk',
  'Micronesia': 'fm',
  'Moldova': 'md',
  'New Guinea': 'pg',
  'North Korea': 'kp',
  'Palestine': 'ps',
  'Pitcairn Islands': 'pn',
  'Reunion': 're',
  'Russia': 'ru',
  'Saint Helena': 'sh',
  'Saint Pierre': 'pm',
  'Saint Vincent': 'vc',
  'Sandwich Islands': 'gs',
  'Sao Tome': 'st',
  'South Korea': 'kr',
  'Svalbard': 'sj',
  'Swaziland': 'sz',
  'Syria': 'sy',
  'Taiwan': 'tw',
  'Tanzania': 'tz',
  'Timor Leste': 'tl',
  'Trinidad': 'tt',
  'Turkey': 'tr',
  'United States': 'us',
  'Us Minor Islands': 'um',
  'Us Virgin Islands': 'vi',
  'Vatican City': 'va',
  'Venezuela': 've',
  'Vietnam': 'vn',
};

// Deleted ISO codes cannot always be mapped to one successor. They remain
// available for reading old database rows but are not offered for new members.
export const LEGACY_COUNTRY_OPTIONS = [
  {key: 'an', value: 'an', flag: 'an', text: 'Antille thuộc Hà Lan'},
];